
name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy
        uses: actions/checkout@v1
      - name: Build
        uses: ./
