
name: Build PDF

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    artifacts:
            paths:
                    - /resume/resume.pdf
    steps:
      - name: Download Files
        uses: actions/checkout@v1
      - name: Compile PDF
        uses: ./
